name: get-cert

on:
  workflow_dispatch:

jobs:
  get_ip:
    runs-on: ubuntu-latest
    steps:
      - name: Get Current IP Address
        id: get_ip
        run: |
          ip_address=$(curl -s ifconfig.me)
          echo "Current IP Address: $ip_address"
          echo "::set-output name=ip::$ip_address"

      - name: Display IP Address
        run: echo "The current IP address is ${{ steps.get_ip.outputs.ip }}"
