name: "Get Cert Cloudflare"
description: "Generate SSL certificates for a domain and update Cloudflare DNS records."
author: "Your Name or Organization"
inputs:
  domain:
    description: "The domain to process SSL for."
    required: true
    default: "example.com"
outputs:
  ip:
    description: "The current public IP address."
runs:
  using: "composite"
  steps:
    - name: "Checkout Repository"
      uses: actions/checkout@v3
    - name: "Get Current IP Address"
      id: get_ip
      run: |
        ip_address=$(curl -s ifconfig.me)
        echo "ip=$ip_address" >> $GITHUB_ENV
    - name: "Update Cloudflare A Record"
      env:
        API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
        DOMAIN: ${{ inputs.domain }}
        NEW_IP: ${{ env.ip }}
      run: |
        # Cloudflare API logic here
    - name: "Generate SSL Certificates"
      run: |
        # Certbot logic here
branding:
  color: "blue"
  icon: "lock"
